global:
  image:
    registry: docker.io
    pullPolicy: IfNotPresent

qotd-service:
  enabled: true
  image:
    repository: quotez
    tag: latest
  service:
    tcpPort: 8017
    udpPort: 8017
    httpPort: 8080
  resources:
    requests:
      cpu: 50m
      memory: 32Mi
    limits:
      cpu: 200m
      memory: 64Mi
  persistence:
    size: 1Gi
    storageClass: ""
  config:
    mode: random
    pollingInterval: 60
    apiEnabled: true
    apiUsername: admin
    apiPassword: quotez

qotd-web:
  enabled: true
  image:
    repository: quotez-web
    tag: latest
  service:
    port: 3000
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 200m
      memory: 128Mi
  env:
    QOTD_API_HOST: qotd-service
    QOTD_API_PORT: "8080"
    QOTD_TCP_HOST: qotd-service
    QOTD_TCP_PORT: "8017"
    QOTD_API_USERNAME: admin
    QOTD_API_PASSWORD: quotez
