enabled: true

replicaCount: 1

image:
  repository: quotez-web
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 3000

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 200m
    memory: 128Mi

env:
  QOTD_API_HOST: qotd-service
  QOTD_API_PORT: "8080"
  QOTD_TCP_HOST: qotd-service
  QOTD_TCP_PORT: "8017"
  QOTD_API_USERNAME: admin
  QOTD_API_PASSWORD: quotez
